version: 2.1

workflows:
  version: 2
  project_cicd:
    jobs:
      - build:
          context:
            - docker-hub

jobs:
  build:
    docker:
      - image: jdrouet/docker-with-buildx:stable
    steps:
      - setup_remote_docker:
          version: 18.09.3
      - checkout
 #     - run:
 #         name: Installing buildx
 #         command: |
 ##           export DOCKER_BUILDKIT=1
  #          docker build --platform=local -o . git://github.com/docker/buildx
  #          mkdir -p ~/.docker/cli-plugins
  #          mv buildx ~/.docker/cli-plugins/docker-buildx
      - run: 
          name: Building image
          command: |
            echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
            docker buildx build --push \
              --platform linux/arm/v7,linux/arm64/v8,linux/amd64 \
              --tag $DOCKER_HUB_USERNAME/multiarch-example:buildx-latest .

